        version: "3.9"
        services:
          postgres:
            image: postgres:12-alpine
            ports:
              - "5432:5432"
            volumes:
              - /var/lib/postgresql
            environment:
              POSTGRES_DB: "habrdb"
              POSTGRES_USER: "habrpguser"
              POSTGRES_PASSWORD: "pgpwd4habr"
